inputs_def:
  - handle: audio_file
    description: "Audio file to transcribe (supports mp3, wav, m4a, flac, etc.)"
    json_schema:
      type: string
      ui:widget: file
    nullable: false

  - handle: model_size
    description: "Whisper model size (larger = more accurate but slower)"
    json_schema:
      type: string
      enum:
        - tiny
        - base
        - small
        - medium
        - large-v2
        - large-v3
    value: base
    nullable: false

  - handle: language
    description: "Language code (e.g., en, zh, ja). Leave empty for auto-detection"
    json_schema:
      type: string
    value:
    nullable: true

  - handle: batch_size
    description: "Batch size for inference (higher = faster but more GPU memory)"
    json_schema:
      type: integer
      minimum: 1
      maximum: 64
    value: 16
    nullable: false

  - handle: enable_alignment
    description: "Enable word-level timestamp alignment (more accurate timestamps)"
    json_schema:
      type: boolean
    value: true
    nullable: false

  - handle: enable_diarization
    description: "Enable speaker diarization (requires HuggingFace token)"
    json_schema:
      type: boolean
    value: false
    nullable: false

  - handle: hf_token
    description: "HuggingFace token (required for diarization feature)"
    json_schema:
      contentMediaType: oomol/secret
      type: string
    value: ${{OO_SECRET:HuggingFace,HuggingFace,HF_TOKEN}}
    nullable: true

  - handle: compute_type
    description: "Computation precision (float16 for GPU, int8 for CPU)"
    json_schema:
      type: string
      enum:
        - float16
        - int8
        - float32
    value: float16
    nullable: false

outputs_def:
  - handle: transcript_text
    description: "Full transcription text"
    json_schema:
      type: string

  - handle: segments
    description: "Transcription segments with timestamps and speaker info"
    json_schema:
      type: string
      contentMediaType: application/json

  - handle: output_file
    description: "Path to the output JSON file"
    json_schema:
      type: string

executor:
  name: python
  options:
    entry: __init__.py
    spawn: false

title: "WhisperX Transcribe"
icon: ":carbon:audio-console:"
description: "Fast automatic speech recognition with word-level timestamps and
  optional speaker diarization. Supports multiple languages and audio formats."
ui:
  default_width: 593.3949020481755
