inputs_def:
  - handle: json_file
    description: "%whisperx-transcription-json-file-with-segments-and-speaker-info%"
    json_schema:
      type: string
      ui:widget: file
    nullable: false

  - handle: include_speaker
    description: "%include-speaker-labels-in-subtitles-e-g-speaker_01%"
    json_schema:
      type: boolean
    value: true
    nullable: false

  - handle: output_path
    description: "%output-srt-file-path-leave-empty-for-auto-generation%"
    json_schema:
      type: string
      ui:widget: save
      ui:options:
        filters:
          - name: SRT
            extensions:
              - srt
        excludeAll: true
    value:
    nullable: true

outputs_def:
  - handle: srt_file
    description: "Path to the generated SRT file"
    json_schema:
      type: string

  - handle: subtitle_count
    description: "Number of subtitle entries generated"
    json_schema:
      type: integer

executor:
  name: python
  options:
    entry: __init__.py
    spawn: false

title: "%generate-srt-subtitles%"
icon: ":carbon:text-annotation-toggle:"
description: "%convert-whisperx-transcription-json-to-srt-subtitle-format-with%"
