inputs_def:
  - handle: json_file
    description: "%whisperx-transcription-json-file-with-segments-and-speaker-info%"
    json_schema:
      type: string
      ui:widget: file
    nullable: false

  - handle: include_speaker
    description: "%include-speaker-labels-in-subtitles-e-g-speaker_01%"
    json_schema:
      type: boolean
    value: null
    nullable: true

  - handle: output_path
    description: "%output-srt-file-path-leave-empty-for-auto-generation%"
    json_schema:
      type: string
      ui:widget: save
      ui:options:
        filters:
          - name: SRT
            extensions:
              - srt
        excludeAll: true
    value: null
    nullable: true

  - handle: use_spacy_segmentation
    description: "Use spaCy for intelligent sentence segmentation"
    json_schema:
      type: boolean
    value: null
    nullable: true

  - handle: spacy_model
    description: "spaCy language model (auto: auto-detect and apply
      language-specific standards)"
    json_schema:
      type: string
      enum:
        - auto
        - en_core_web_sm
        - zh_core_web_sm
        - ja_core_news_sm
        - de_core_news_sm
        - fr_core_news_sm
        - es_core_news_sm
    value: null
    nullable: true

  - handle: subtitle_language_preset
    description: "Language preset for subtitle standards (auto: detect from text)"
    json_schema:
      type: string
      enum:
        - auto
        - english
        - chinese
        - japanese
        - custom
    value: null
    nullable: true

  - handle: max_chars_per_subtitle
    description: "Maximum characters per subtitle (EN: 42-84, CN: 15-20). Auto-set
      by language preset."
    json_schema:
      type: integer
      minimum: 10
      maximum: 150
    value: null
    nullable: true

  - handle: max_duration_per_subtitle
    description: "Maximum duration per subtitle in seconds. Auto-set by language preset."
    json_schema:
      type: number
      minimum: 0
      maximum: 10
    value: null
    nullable: true

  - handle: chars_per_second
    description: "Characters per second reading speed (EN: 17-21, CN: ~4). Auto-set
      by language preset."
    json_schema:
      type: number
      minimum: 1
      maximum: 50
    value: null
    nullable: true

  - handle: max_words_per_subtitle
    description: "Maximum words per subtitle (EN only: 7 single line / 15 double
      line, 0 = no limit)"
    json_schema:
      type: integer
      minimum: 0
      maximum: 30
    value: null
    nullable: true

outputs_def:
  - handle: srt_file
    description: "Path to the generated SRT file"
    json_schema:
      type: string

  - handle: subtitle_count
    description: "Number of subtitle entries generated"
    json_schema:
      type: integer

executor:
  name: python
  options:
    entry: __init__.py
    spawn: false

title: "%generate-srt-subtitles%"
icon: ":carbon:text-annotation-toggle:"
description: "%convert-whisperx-transcription-json-to-srt-subtitle-format-with%"
